### ISSUE TITLE
Provide convenient method to construct the Presenter if it has non-empty constructors in case of fragment.

### ISSUE THREAD

**Issue by msimar** [joaquim-verges/Helium#12]
Added for reference
https://proandroiddev.com/viewmodel-with-dagger2-architecture-components-2e06f06c9455

Otherwise end up issues
https://github.com/googlesamples/android-architecture-components/issues/207

**Comment by joaquim-verges** [comment]
good point, I have it for Activity but not for Fragment. I'll add that asap. Thanks!

In the meantime you can use `ViewModelProviders.of(fragment)` instead of `RetainedPresenters.get()` to pass in your presenter factory. `RetainedPresenters` is really just a convenience wrapper on top of `ViewModelProviders`.

**Comment by msimar** [comment]
Yeah, I noticed RetainedPresenters and already using ViewModelProviders.
