### ISSUE TITLE
[Question] Architecture Questions

### ISSUE THREAD

**Issue by OllenDev** [joaquim-verges/Helium#20]
# Architecture Questions

1. How would you observe things that have a lifecycle in the ViewDelegate? A good example of this would be a TextWatcher that needs to be added and removed based on the Android Lifecycle.

1. Navigation to different `Fragments` or `Activities` requires an `Activity` object. There doesn't seem to be an easy way to respond to `ViewState` events that would trigger some type of navigation or transition inside the view delegate. Have you thought about how to handle this?

1. `OnSavedInstance` state in `Activities` and `Fragments` persists state for when the OS needs to kill an activity. Have you thought about how to handle this?

1. How would you handle events that start in the `Activity` or `Fragment`? Method calls like onBackPressed or possibly `BroadcastReceivers` would most likely originate in an `Activity` and need to notify the `ViewDelegate` or `Presenter`.

I've got some ideas on how to solve each of the questions above, but I was hoping you may have already thought about it. It'd be cool to figure out a slick way to integrate answers to these questions into the framework.

Thanks and I'm really digging the way this works!

**Comment by joaquim-verges** [comment]
Hi @OllenDev thanks for your questions!

> 1. How would you observing things that have a lifecycle in the ViewDelegate? A good example of this would be a TextWatcher that needs to be added and removed based on the Android Lifecycle.

ViewDelegates should be self contained, and never retained by any presenters for longer than the authorized "attached" lifecycle (handled by [AutoDispose](https://github.com/uber/AutoDispose) ). When you call `presenter.attach(viewDelegate)` in `onCreate`, AutoDispose will make sure the subscriptions are disposed in `onDestroy`, similarly, if you attach in `onResume`, disposing will happen in `onPause` automatically.

This means that if you add a TextWatcher to a view inside a view delegate, it will live as long as the view delegate is attached. As soon as the presenter disposes its subscription to the ViewDelegate,  there should be no more references to it, and the GC can go ahead and clean that up, including the TextWatcher that was attached.

So in short, ViewDelegates don't really have an explicit lifecycle, only object creation and destruction, and any object within it will get freed up as long as there's no more references to that view delegate.

That means that you don't need to explicitly remove a TextWatcher added inside a view delegate, it will get cleaned up whenever the view delegate is no longer held by a presenter.

Same thing for things like scroll listeners and other Android view callbacks.

> 2. Navigation to different `Fragments` or `Activities` requires an `Activity` object. There doesn't seem to be an easy way to respond to `ViewState` events that would trigger some type of navigation or transition inside the view delegate. Have you thought about how to handle this?

In my experience, navigation actions are triggered by `ViewEvents` (something coming from the ViewDelegate), not `ViewState` (state changes in the presenter).

One thing I've been doing is passing the `Context` within `ViewEvent` objects, so that the presenter can do things like start a new activity or add a new fragment when it receives that ViewEvent, using the context passed along with it.

If you have a use case that legitimately triggers a navigation from a presenter state change, say on API request error for example, then you can always push an Error state to the view delegate, which in turn will push a `ViewEvent` like `NavigateTo(context, destination)`.

> 3. `OnSavedInstance` state in `Activities` and `Fragments` persists state for when the OS needs to kill an activity. Have you thought about how to handle this?

This is a great question, and something I haven't tackled yet. My approach off the top of my head for this would be:

- persist the most minimal piece of info (like an id or something) on `onSaveInstanceState`, probably reading it from the current presenter state (would have to expose it).
- in `onRestoreInstanceState`, call an explicit `presenter.restoreState(savedData)` which would perform what it would need to do to restore the corresponding state, and push it down to the UI.

I'm hesitant to bake this into the base classes, since in most cases you don't need it (activity/fragment stack restoration is usually enough and you get that for free), but I might re-consider if more people ask for it.

> 4. How would you handle events that start in the `Activity` or `Fragment`? Method calls like onBackPressed or possibly `BroadcastReceivers` would most likely originate in an `Activity` and need to notify the `ViewDelegate` or `Presenter`.

Great question again. This is definitely something I'm thinking to bake into the framework. For now the easiest is to manually call a view delegate method from `Activity.onBackPressed` that would fire a custom `BackPressed` event.

But I would like for this to be part of the framework, not 100% sure how yet. But the simplest would probably be something an extension function like `Activity.registerForBackPressEvents(viewDelegate)` and a corresponding `onBackPressedEvent()` method to override in `BaseViewDelegate` that you can do whatever you want with. Open to other ideas on this though.

`BroadcastReceivers` is another interesting one which I'd like to integrate in the framework. Again not settled on the implementation, but I'd like to make a reactive version of a `BroadcastReceiver` that would register/unregister itself on its own (using `LifecycleObserver`) and could push its updates to a static Rx bus that presenters could subscribe to. Open to suggestions on that one too.

Thanks again for the great questions!
